"""Runtime-facing exports for distributed execution, manifests, staging, and transport.

This package uses lazy attribute loading to avoid circular imports during capture-time
module initialization, especially for:

capture.py -> hexgen_core.config -> hexgen_core.__init__ -> pipeline/hybrid modules -> capture.py
"""

from importlib import import_module

_LAZY_MODULES = (
    "qwen3vl_tp_runtime.hexgen_core.config",
    "qwen3vl_tp_runtime.hexgen_core.distributed",
    "qwen3vl_tp_runtime.hexgen_core.gen_hetero_groups",
    "qwen3vl_tp_runtime.hexgen_core.schema",
    "qwen3vl_tp_runtime.hexgen_core.stage",
    "qwen3vl_tp_runtime.hexgen_core.transport",
    "qwen3vl_tp_runtime.hexgen_core.modules.pipeline_parallel",
    "qwen3vl_tp_runtime.hexgen_core.modules.tensor_parallel",
    "qwen3vl_tp_runtime.hexgen_core.modules.hybrid_parallel",
)

__all__ = [
    "MODEL_PATH",
    "FRAME_DIR",
    "FULL_LAYER_BUNDLE_PATH",
    "LAYER_RANGE_BUNDLE_PATH",
    "MULTIMODAL_DECODE_BUNDLE_PATH",
    "MULTIMODAL_DECODE_HYBRID_BUNDLE_DIR",
    "MULTIMODAL_DECODE_HYBRID_MANIFEST_PATH",
    "MULTIMODAL_DECODE_PIPELINE_BUNDLE_DIR",
    "MULTIMODAL_DECODE_PIPELINE_MANIFEST_PATH",
    "MULTIMODAL_PREFILL_BUNDLE_PATH",
    "MULTIMODAL_PREFILL_HYBRID_BUNDLE_DIR",
    "MULTIMODAL_PREFILL_HYBRID_MANIFEST_PATH",
    "MULTIMODAL_PREFILL_PIPELINE_BUNDLE_DIR",
    "MULTIMODAL_PREFILL_PIPELINE_MANIFEST_PATH",
    "TEXT_DECODE_BUNDLE_PATH",
    "TEXT_DECODE_HYBRID_BUNDLE_DIR",
    "TEXT_DECODE_HYBRID_MANIFEST_PATH",
    "TEXT_DECODE_PIPELINE_BUNDLE_DIR",
    "TEXT_DECODE_PIPELINE_MANIFEST_PATH",
    "TEXT_GENERATE_BUNDLE_PATH",
    "TEXT_GENERATE_HYBRID_BUNDLE_DIR",
    "TEXT_GENERATE_HYBRID_MANIFEST_PATH",
    "TEXT_GENERATE_PIPELINE_BUNDLE_DIR",
    "TEXT_GENERATE_PIPELINE_MANIFEST_PATH",
    "TEXT_PREFILL_BUNDLE_PATH",
    "TEXT_PREFILL_HYBRID_BUNDLE_DIR",
    "TEXT_PREFILL_HYBRID_MANIFEST_PATH",
    "TEXT_PREFILL_PIPELINE_BUNDLE_DIR",
    "TEXT_PREFILL_PIPELINE_MANIFEST_PATH",
    "TEXT_HYBRID_BUNDLE_DIR",
    "TEXT_HYBRID_MANIFEST_PATH",
    "TEXT_PIPELINE_BUNDLE_DIR",
    "TEXT_PIPELINE_MANIFEST_PATH",
    "TEXT_STAGE_BUNDLE_PATH",
    "TEXT_STAGE0_BUNDLE_PATH",
    "TEXT_STAGE1_BUNDLE_PATH",
    "getenv_int",
    "init_dist",
    "get_device",
    "all_reduce_cpu",
    "broadcast_cpu",
    "parse_tp_degrees",
    "build_stage_rank_groups",
    "build_pp_rank_groups",
    "build_p2p_lists",
    "build_hybrid_layout",
    "StageSpec",
    "BoundaryStats",
    "TextPipelineManifest",
    "TextGeneratePipelineRunner",
    "TextPipelineRunner",
    "TextTensorParallelRunner",
    "HybridLayout",
    "TextHybridManifest",
    "HybridRankContext",
    "PayloadSummary",
    "StageHandoffPayload",
    "build_stage_bundle_path",
    "parse_stage_range",
    "parse_stage_ranges",
    "prepare_multimodal_decode_pipeline",
    "prepare_multimodal_prefill_pipeline",
    "prepare_text_decode_pipeline",
    "prepare_text_generate_pipeline",
    "prepare_text_prefill_pipeline",
    "prepare_text_pipeline",
    "load_pipeline_manifest",
    "load_stage_bundle_by_index",
    "load_stage_bundle_for_rank",
    "run_text_generate_pipeline_rank",
    "run_text_pipeline_rank",
    "load_text_stage_bundle",
    "run_text_tensor_parallel_rank",
    "prepare_multimodal_decode_hybrid",
    "prepare_multimodal_prefill_hybrid",
    "prepare_text_decode_hybrid",
    "prepare_text_generate_hybrid",
    "prepare_text_prefill_hybrid",
    "prepare_text_hybrid",
    "load_hybrid_manifest",
    "init_stage_groups",
    "resolve_rank_stage",
    "TextHybridRunner",
    "run_text_hybrid_rank",
    "StageBundleView",
    "as_stage_bundle_view",
    "get_stage_type",
    "get_stage_input",
    "get_stage_output",
    "build_stage_bundle",
    "build_stage_handoff_target_dtypes",
    "build_stage_handoff_payload",
    "apply_stage_handoff_payload",
    "run_stage",
    "run_stage_tp",
    "trace_stage",
    "trace_stage_tp",
    "StageHandoffMessage",
    "StageHandoffTransport",
    "TensorPayload",
    "send_payload",
    "recv_payload",
    "send_tensor",
    "recv_tensor",
    "send_hidden_states",
    "recv_hidden_states",
    "tensor_diff_stats",
]


def __getattr__(name: str):
    for module_name in _LAZY_MODULES:
        module = import_module(module_name)
        if hasattr(module, name):
            value = getattr(module, name)
            globals()[name] = value
            return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
