"""Default local paths used by the prototype capture and runtime entrypoints."""

MODEL_PATH = "/mnt/ssd/models/Qwen/Qwen3-VL-4B-Instruct"
FRAME_DIR = "/mnt/ssd/code/Qwen3_vl/frames"
FULL_LAYER_BUNDLE_PATH = "/mnt/ssd/code/Qwen3_vl/qwen3vl_full_layer_case.pt"
LAYER_RANGE_BUNDLE_PATH = "/mnt/ssd/code/Qwen3_vl/qwen3vl_layer_range_case.pt"
TEXT_STAGE_BUNDLE_PATH = "/mnt/ssd/code/Qwen3_vl/qwen3vl_text_stage_case.pt"
TEXT_PREFILL_BUNDLE_PATH = "/mnt/ssd/code/Qwen3_vl/qwen3vl_text_prefill_case.pt"
TEXT_STAGE0_BUNDLE_PATH = "/mnt/ssd/code/Qwen3_vl/qwen3vl_text_stage0_case.pt"
TEXT_STAGE1_BUNDLE_PATH = "/mnt/ssd/code/Qwen3_vl/qwen3vl_text_stage1_case.pt"
TEXT_PIPELINE_BUNDLE_DIR = "/mnt/ssd/code/Qwen3_vl/qwen3vl_text_pipeline"
TEXT_PIPELINE_MANIFEST_PATH = "/mnt/ssd/code/Qwen3_vl/qwen3vl_text_pipeline_manifest.pt"
TEXT_PREFILL_PIPELINE_BUNDLE_DIR = "/mnt/ssd/code/Qwen3_vl/qwen3vl_text_prefill_pipeline"
TEXT_PREFILL_PIPELINE_MANIFEST_PATH = "/mnt/ssd/code/Qwen3_vl/qwen3vl_text_prefill_pipeline_manifest.pt"
TEXT_HYBRID_BUNDLE_DIR = "/mnt/ssd/code/Qwen3_vl/qwen3vl_text_hybrid"
TEXT_HYBRID_MANIFEST_PATH = "/mnt/ssd/code/Qwen3_vl/qwen3vl_text_hybrid_manifest.pt"
TEXT_PREFILL_HYBRID_BUNDLE_DIR = "/mnt/ssd/code/Qwen3_vl/qwen3vl_text_prefill_hybrid"
TEXT_PREFILL_HYBRID_MANIFEST_PATH = "/mnt/ssd/code/Qwen3_vl/qwen3vl_text_prefill_hybrid_manifest.pt"
